[package]
name = "mini-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miniserde = "0.1.34"
serde = { version = "1.0.193", features = ["derive"]}
