[package]
name = "stripe_billing"
version.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
path = "src/mod.rs"

[dependencies]
serde.workspace = true
smol_str.workspace = true
serde_json.workspace = true
stripe_types = {path = "../../stripe_types"}

http-types.workspace = true
async-stripe = {path = "../../async-stripe"}


stripe_shared = {path = "../../generated/stripe_shared"}


[features]
runtime-tokio-hyper = ["async-stripe/runtime-tokio-hyper"]
runtime-tokio-hyper-rustls = ["async-stripe/runtime-tokio-hyper-rustls"]
runtime-tokio-hyper-rustls-webpki = ["async-stripe/runtime-tokio-hyper-rustls-webpki"]
runtime-blocking = ["async-stripe/runtime-blocking"]
runtime-blocking-rustls = ["async-stripe/runtime-blocking-rustls"]
runtime-blocking-rustls-webpki = ["async-stripe/runtime-blocking-rustls-webpki"]
runtime-async-std-surf = ["async-stripe/runtime-async-std-surf"]

billing_portal_configuration = []
billing_portal_session = []
credit_note = []
credit_note_line_item = []
invoice = []
invoice_item = []
invoice_line_item = []
plan = []
quote = []
subscription = []
subscription_item = []
subscription_schedule = []
tax_id = []
test_helpers_test_clock = []
usage_record = []
usage_record_summary = []

full = ["billing_portal_configuration",
"billing_portal_session",
"credit_note",
"credit_note_line_item",
"invoice",
"invoice_item",
"invoice_line_item",
"plan",
"quote",
"subscription",
"subscription_item",
"subscription_schedule",
"tax_id",
"test_helpers_test_clock",
"usage_record",
"usage_record_summary"]


[package.metadata.docs.rs]
features = ["runtime-tokio-hyper", "full"]

